Generated by the CoffeeCup Web Editor - www.coffeecup.com
			

Description...
			
			
@created:           02/03/2015 - 21:08:26
@today:             02/03/2015
@project:           No Project
@path:              /Users/davidnie/02092015/OutlawSass/simplepush.js
			
@author:            Your name
@company:           Your company
@Copyright:         A copyright notice
			
@version:           $Revision:$
